[workspace]
exclude = ["programs/margin-trade"]

[programs.localnet]
mango_v4 = "4MTevvuuqC2sZtckP6RPeLZcqV3JyqoF3N5fswzc3NmT"

[programs.devnet]
mango_v4 = "4MTevvuuqC2sZtckP6RPeLZcqV3JyqoF3N5fswzc3NmT"

[features]
seeds = true

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 anchor-tests/*.ts"

[test.validator]
limit_ledger_size = "10000000"
