[package]
name = "mango-v4-settler"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "settler"
path = "src/main.rs"

[dependencies]
anchor-lang = { workspace = true }
anchor-client = { workspace = true }
anyhow = "1.0"
arrayref = "0.3.6"
async-channel = "1.6"
async-stream = "0.2"
async-trait = "0.1"
bincode = "1.3.3"
bs58 = "0.3.1"
bytemuck = "^1.7.2"
bytes = "1.0"
clap = { version = "3.1.8", features = ["derive", "env"] }
dotenv = "0.15.0"
fixed = { workspace = true, features = ["serde"] }
futures = "0.3.17"
futures-core = "0.3"
futures-util = "0.3"
itertools = "0.10.3"
jemallocator = "0.3.2"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ws", "http", "tls"] }
mango-v4 = { path = "../../programs/mango-v4", features = ["client"] }
mango-v4-client = { path = "../../lib/client" }
once_cell = "1.12.0"
priority-queue = "1.3.1"
pyth-sdk-solana = { workspace = true }
rand = "0.7"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.68"
serum_dex = { workspace = true, features = ["no-entrypoint", "program"] }
shellexpand = "2.1.0"
solana-account-decoder = { workspace = true }
solana-client = { workspace = true }
solana-logger = { workspace = true }
solana-rpc = { workspace = true }
solana-sdk = { workspace = true }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.9"}
tokio-tungstenite = "0.16.1"
tracing = "0.1"
